In [129]:
import pandas as pd

In [130]:
import pandas as pd

In [131]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [132]:
df=pd.read_csv("https://raw.githubusercontent.com/shsarv/Machine-Learning-Projects/main/Diabetes%20Prediction%20%5BEND%202%20END%5D/dataset/kaggle_diabetes.csv")

In [133]:
import pandas as pd

In [134]:
df["BloodPressure"].value_counts()


BloodPressure
74     145
70     144
78     128
68     125
64     120
72     118
80      98
62      94
76      93
60      92
0       90
82      83
88      67
66      65
84      61
90      55
58      54
86      53
50      31
56      31
54      31
52      29
75      20
65      19
94      18
85      14
48      13
92      12
44      11
106      9
100      9
98       8
96       8
110      7
46       6
104      5
108      5
55       4
61       4
114      3
102      3
30       3
122      3
38       3
95       2
24       2
40       2
Name: count, dtype: int64

In [135]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [136]:
y=df["Outcome"]
x=df.drop("Outcome",axis=1)

In [137]:
from sklearn.model_selection import train_test_split


In [138]:
pip install scikit-learn


[notice] A new release of pip available: 22.3 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [139]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [140]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [141]:
lr=LogisticRegression()
dt=DecisionTreeClassifier()

In [142]:
lr.fit(x_train,y_train)
dt.fit(x_train,y_train)

c:\Users\91863\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [143]:
print("Logistic:",lr.score(x_train,y_train),lr.score(x_test,y_test))
print("Decision:",dt.score(x_train,y_train),dt.score(x_test,y_test))

Logistic: 0.7673333333333333 0.794
Decision: 1.0 0.966


In [144]:
from sklearn.model_selection import cross_val_score

In [145]:
cross_val_score(lr,x_test,y_test,cv=5)

c:\Users\91863\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\91863\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.74, 0.83, 0.8 , 0.78, 0.81])

In [146]:
from sklearn.model_selection import GridSearchCV

In [147]:
grid_search =GridSearchCV(estimator=lr,param_grid=param_grid,cv=5,scoring='accuracy')
grid_search.fit(x_train,y_train)
best_params = grid_search.best_params_
print("Best Parameters: ",best_params)

Best Parameters:  {'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}


In [148]:
param_grid = {
    "C" : [0.01,0.1,1,10,1000],
    "penalty":['l2','l1'],
    'solver':['liblinear']
}

In [149]:
grid_search.score(x_test,y_test)

0.79

In [150]:
from sklearn.metrics import classification_report

In [151]:
print(classification_report(y_test,lr.predict(x_test)))

              precision    recall  f1-score   support

           0       0.80      0.91      0.85       320
           1       0.78      0.59      0.68       180

    accuracy                           0.79       500
   macro avg       0.79      0.75      0.76       500
weighted avg       0.79      0.79      0.79       500



In [152]:
from sklearn.metrics import confusion_matrix

In [153]:
confusion_matrix(y_test,lr.predict(x_test))

array([[290,  30],
       [ 73, 107]])

In [154]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

print(confusion_matrix(y_test,lr.predict(x_test)))
print(accuracy_score(y_test,lr.predict(x_test)))
print(precision_score(y_test,lr.predict(x_test)))
print(recall_score(y_test,lr.predict(x_test)))
print(f1_score(y_test,lr.predict(x_test)))

[[290  30]
 [ 73 107]]
0.794
0.781021897810219
0.5944444444444444
0.6750788643533123


In [155]:
import pickle
with open('model.pickle','wb') as model_file:
    pickle.dump(lr,model_file)

In [156]:
df["BloodPressure"].max()

np.int64(122)

In [157]:
zero_counts = (df == 0).sum()
print(zero_counts)

Pregnancies                  301
Glucose                       13
BloodPressure                 90
SkinThickness                573
Insulin                      956
BMI                           28
DiabetesPedigreeFunction       0
Age                            0
Outcome                     1316
dtype: int64


In [158]:
df['BloodPressure'].fillna(df['BloodPressure'].mode()[0],inplace=True)

C:\Users\91863\AppData\Local\Temp\ipykernel_15948\2012243801.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BloodPressure'].fillna(df['BloodPressure'].mode()[0],inplace=True)


In [159]:
df['BloodPressure'] = df['BloodPressure'].replace(0, df['BloodPressure'].mean())

In [160]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138        62.0000             35        0  33.6   
1               0       84        82.0000             31      125  38.2   
2               0      145        69.1455              0        0  44.2   
3               0      135        68.0000             42      250  42.3   
4               1      139        62.0000             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75        64.0000             24       55  29.7   
1996            8      179        72.0000             42      130  32.7   
1997            6       85        78.0000              0        0  31.2   
1998            0      129       110.0000             46      130  67.1   
1999            2       81        72.0000             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [161]:
df['BMI'] = df['BMI'].replace(0, df['BMI'].mean())

In [162]:
(df==0).sum()

Pregnancies                  301
Glucose                       13
BloodPressure                  0
SkinThickness                573
Insulin                      956
BMI                            0
DiabetesPedigreeFunction       0
Age                            0
Outcome                     1316
dtype: int64

In [163]:
df['SkinThickness'] = df['SkinThickness'].replace(0, df['SkinThickness'].mean())

In [164]:
## Project

In [165]:
y=df["Outcome"]
x=df.drop("Outcome",axis=1)

In [166]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [167]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [168]:
lr=LogisticRegression()
dt=DecisionTreeClassifier()

In [169]:
lr.fit(x_train,y_train)
dt.fit(x_train,y_train)

c:\Users\91863\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [170]:
print("Logistic:",lr.score(x_train,y_train),lr.score(x_test,y_test))
print("DecisionTree:",dt.score(x_train,y_train),dt.score(x_test,y_test))

Logistic: 0.764 0.786
DecisionTree: 1.0 0.966


In [171]:
from sklearn.model_selection import cross_val_score

In [172]:
cross_val_score(lr,x_test,y_test,cv=5)

c:\Users\91863\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\91863\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.76, 0.85, 0.83, 0.72, 0.77])

In [173]:
cross_val_score(dt,x_test,y_test,cv=5)

array([0.76, 0.79, 0.9 , 0.82, 0.78])

In [174]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138        62.0000         35.000        0  33.6   
1               0       84        82.0000         31.000      125  38.2   
2               0      145        69.1455         20.935        0  44.2   
3               0      135        68.0000         42.000      250  42.3   
4               1      139        62.0000         41.000      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75        64.0000         24.000       55  29.7   
1996            8      179        72.0000         42.000      130  32.7   
1997            6       85        78.0000         20.935        0  31.2   
1998            0      129       110.0000         46.000      130  67.1   
1999            2       81        72.0000         15.000       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [178]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure               float64
SkinThickness               float64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [177]:
(df==0).sum()

Pregnancies                  301
Glucose                       13
BloodPressure                  0
SkinThickness                  0
Insulin                      956
BMI                            0
DiabetesPedigreeFunction       0
Age                            0
Outcome                     1316
dtype: int64

In [179]:
from sklearn.model_selection import GridSearchCV

In [180]:
grid_search =GridSearchCV(estimator=lr,param_grid=param_grid,cv=5,scoring='accuracy')
grid_search.fit(x_train,y_train)
best_params = grid_search.best_params_
print("Best Parameters: ",best_params)

Best Parameters:  {'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}


In [184]:
grid_search.score(x_test,y_test)

0.778